/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PageIdImport } from './routes/$pageId'

// Create Virtual Routes

const OnboardingLazyImport = createFileRoute('/onboarding')()
const DesignerLazyImport = createFileRoute('/designer')()
const DashboardLazyImport = createFileRoute('/dashboard')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const OnboardingLazyRoute = OnboardingLazyImport.update({
  path: '/onboarding',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/onboarding.lazy').then((d) => d.Route))

const DesignerLazyRoute = DesignerLazyImport.update({
  path: '/designer',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/designer.lazy').then((d) => d.Route))

const DashboardLazyRoute = DashboardLazyImport.update({
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/dashboard').then((d) => d.Route))

const PageIdRoute = PageIdImport.update({
  path: '/$pageId',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/$pageId': {
      id: '/$pageId'
      path: '/$pageId'
      fullPath: '/$pageId'
      preLoaderRoute: typeof PageIdImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLazyImport
      parentRoute: typeof rootRoute
    }
    '/designer': {
      id: '/designer'
      path: '/designer'
      fullPath: '/designer'
      preLoaderRoute: typeof DesignerLazyImport
      parentRoute: typeof rootRoute
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/$pageId': typeof PageIdRoute
  '/dashboard': typeof DashboardLazyRoute
  '/designer': typeof DesignerLazyRoute
  '/onboarding': typeof OnboardingLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/$pageId': typeof PageIdRoute
  '/dashboard': typeof DashboardLazyRoute
  '/designer': typeof DesignerLazyRoute
  '/onboarding': typeof OnboardingLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/$pageId': typeof PageIdRoute
  '/dashboard': typeof DashboardLazyRoute
  '/designer': typeof DesignerLazyRoute
  '/onboarding': typeof OnboardingLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$pageId' | '/dashboard' | '/designer' | '/onboarding'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$pageId' | '/dashboard' | '/designer' | '/onboarding'
  id: '__root__' | '/' | '/$pageId' | '/dashboard' | '/designer' | '/onboarding'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  PageIdRoute: typeof PageIdRoute
  DashboardLazyRoute: typeof DashboardLazyRoute
  DesignerLazyRoute: typeof DesignerLazyRoute
  OnboardingLazyRoute: typeof OnboardingLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  PageIdRoute: PageIdRoute,
  DashboardLazyRoute: DashboardLazyRoute,
  DesignerLazyRoute: DesignerLazyRoute,
  OnboardingLazyRoute: OnboardingLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$pageId",
        "/dashboard",
        "/designer",
        "/onboarding"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/$pageId": {
      "filePath": "$pageId.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard.lazy.tsx"
    },
    "/designer": {
      "filePath": "designer.lazy.tsx"
    },
    "/onboarding": {
      "filePath": "onboarding.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
