/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const OnboardingLazyImport = createFileRoute('/onboarding')()
const DesignerLazyImport = createFileRoute('/designer')()
const DashboardLazyImport = createFileRoute('/dashboard')()
const PageIdLazyImport = createFileRoute('/$pageId')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const OnboardingLazyRoute = OnboardingLazyImport.update({
  path: '/onboarding',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/onboarding.lazy').then((d) => d.Route))

const DesignerLazyRoute = DesignerLazyImport.update({
  path: '/designer',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/designer.lazy').then((d) => d.Route))

const DashboardLazyRoute = DashboardLazyImport.update({
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/dashboard.lazy').then((d) => d.Route))

const PageIdLazyRoute = PageIdLazyImport.update({
  path: '/$pageId',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/$pageId.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/$pageId': {
      id: '/$pageId'
      path: '/$pageId'
      fullPath: '/$pageId'
      preLoaderRoute: typeof PageIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLazyImport
      parentRoute: typeof rootRoute
    }
    '/designer': {
      id: '/designer'
      path: '/designer'
      fullPath: '/designer'
      preLoaderRoute: typeof DesignerLazyImport
      parentRoute: typeof rootRoute
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  PageIdLazyRoute,
  DashboardLazyRoute,
  DesignerLazyRoute,
  OnboardingLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$pageId",
        "/dashboard",
        "/designer",
        "/onboarding"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/$pageId": {
      "filePath": "$pageId.lazy.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard.lazy.tsx"
    },
    "/designer": {
      "filePath": "designer.lazy.tsx"
    },
    "/onboarding": {
      "filePath": "onboarding.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
