/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as InteractiveContentDesignerRouteImport } from './routes/interactive-content-designer'
import { Route as PageIdRouteImport } from './routes/$pageId'

const PreviewLazyRouteImport = createFileRoute('/preview')()
const OnboardingLazyRouteImport = createFileRoute('/onboarding')()

const PreviewLazyRoute = PreviewLazyRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/preview.lazy').then((d) => d.Route))
const OnboardingLazyRoute = OnboardingLazyRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/onboarding.lazy').then((d) => d.Route))
const InteractiveContentDesignerRoute =
  InteractiveContentDesignerRouteImport.update({
    id: '/interactive-content-designer',
    path: '/interactive-content-designer',
    getParentRoute: () => rootRouteImport,
  } as any)
const PageIdRoute = PageIdRouteImport.update({
  id: '/$pageId',
  path: '/$pageId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/$pageId': typeof PageIdRoute
  '/interactive-content-designer': typeof InteractiveContentDesignerRoute
  '/onboarding': typeof OnboardingLazyRoute
  '/preview': typeof PreviewLazyRoute
}
export interface FileRoutesByTo {
  '/$pageId': typeof PageIdRoute
  '/interactive-content-designer': typeof InteractiveContentDesignerRoute
  '/onboarding': typeof OnboardingLazyRoute
  '/preview': typeof PreviewLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$pageId': typeof PageIdRoute
  '/interactive-content-designer': typeof InteractiveContentDesignerRoute
  '/onboarding': typeof OnboardingLazyRoute
  '/preview': typeof PreviewLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$pageId'
    | '/interactive-content-designer'
    | '/onboarding'
    | '/preview'
  fileRoutesByTo: FileRoutesByTo
  to: '/$pageId' | '/interactive-content-designer' | '/onboarding' | '/preview'
  id:
    | '__root__'
    | '/$pageId'
    | '/interactive-content-designer'
    | '/onboarding'
    | '/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PageIdRoute: typeof PageIdRoute
  InteractiveContentDesignerRoute: typeof InteractiveContentDesignerRoute
  OnboardingLazyRoute: typeof OnboardingLazyRoute
  PreviewLazyRoute: typeof PreviewLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interactive-content-designer': {
      id: '/interactive-content-designer'
      path: '/interactive-content-designer'
      fullPath: '/interactive-content-designer'
      preLoaderRoute: typeof InteractiveContentDesignerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$pageId': {
      id: '/$pageId'
      path: '/$pageId'
      fullPath: '/$pageId'
      preLoaderRoute: typeof PageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  PageIdRoute: PageIdRoute,
  InteractiveContentDesignerRoute: InteractiveContentDesignerRoute,
  OnboardingLazyRoute: OnboardingLazyRoute,
  PreviewLazyRoute: PreviewLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
