/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as PageIdRouteImport } from './routes/$pageId'
import { Route as IndexRouteImport } from './routes/index'

const PreviewLazyRouteImport = createFileRoute('/preview')()
const OnboardingLazyRouteImport = createFileRoute('/onboarding')()

const PreviewLazyRoute = PreviewLazyRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/preview.lazy').then((d) => d.Route))
const OnboardingLazyRoute = OnboardingLazyRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/onboarding.lazy').then((d) => d.Route))
const PageIdRoute = PageIdRouteImport.update({
  id: '/$pageId',
  path: '/$pageId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$pageId': typeof PageIdRoute
  '/onboarding': typeof OnboardingLazyRoute
  '/preview': typeof PreviewLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$pageId': typeof PageIdRoute
  '/onboarding': typeof OnboardingLazyRoute
  '/preview': typeof PreviewLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$pageId': typeof PageIdRoute
  '/onboarding': typeof OnboardingLazyRoute
  '/preview': typeof PreviewLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$pageId' | '/onboarding' | '/preview'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$pageId' | '/onboarding' | '/preview'
  id: '__root__' | '/' | '/$pageId' | '/onboarding' | '/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PageIdRoute: typeof PageIdRoute
  OnboardingLazyRoute: typeof OnboardingLazyRoute
  PreviewLazyRoute: typeof PreviewLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$pageId': {
      id: '/$pageId'
      path: '/$pageId'
      fullPath: '/$pageId'
      preLoaderRoute: typeof PageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PageIdRoute: PageIdRoute,
  OnboardingLazyRoute: OnboardingLazyRoute,
  PreviewLazyRoute: PreviewLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
