/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from "@tanstack/react-router"

// Import Routes

import { Route as rootRoute } from "./routes/__root"
import { Route as InteractiveContentDesignerImport } from "./routes/interactive-content-designer"
import { Route as PageIdImport } from "./routes/$pageId"

// Create Virtual Routes

const PreviewLazyImport = createFileRoute("/preview")()
const OnboardingLazyImport = createFileRoute("/onboarding")()
const IndexLazyImport = createFileRoute("/")()

// Create/Update Routes

const PreviewLazyRoute = PreviewLazyImport.update({
	path: "/preview",
	getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/preview.lazy").then((d) => d.Route))

const OnboardingLazyRoute = OnboardingLazyImport.update({
	path: "/onboarding",
	getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/onboarding.lazy").then((d) => d.Route))

const InteractiveContentDesignerRoute = InteractiveContentDesignerImport.update({
	path: "/interactive-content-designer",
	getParentRoute: () => rootRoute,
} as any)

const PageIdRoute = PageIdImport.update({
	path: "/$pageId",
	getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
	path: "/",
	getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/index.lazy").then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
	interface FileRoutesByPath {
		"/": {
			id: "/"
			path: "/"
			fullPath: "/"
			preLoaderRoute: typeof IndexLazyImport
			parentRoute: typeof rootRoute
		}
		"/$pageId": {
			id: "/$pageId"
			path: "/$pageId"
			fullPath: "/$pageId"
			preLoaderRoute: typeof PageIdImport
			parentRoute: typeof rootRoute
		}
		"/interactive-content-designer": {
			id: "/interactive-content-designer"
			path: "/interactive-content-designer"
			fullPath: "/interactive-content-designer"
			preLoaderRoute: typeof InteractiveContentDesignerImport
			parentRoute: typeof rootRoute
		}
		"/onboarding": {
			id: "/onboarding"
			path: "/onboarding"
			fullPath: "/onboarding"
			preLoaderRoute: typeof OnboardingLazyImport
			parentRoute: typeof rootRoute
		}
		"/preview": {
			id: "/preview"
			path: "/preview"
			fullPath: "/preview"
			preLoaderRoute: typeof PreviewLazyImport
			parentRoute: typeof rootRoute
		}
	}
}

// Create and export the route tree

export interface FileRoutesByFullPath {
	"/": typeof IndexLazyRoute
	"/$pageId": typeof PageIdRoute
	"/interactive-content-designer": typeof InteractiveContentDesignerRoute
	"/onboarding": typeof OnboardingLazyRoute
	"/preview": typeof PreviewLazyRoute
}

export interface FileRoutesByTo {
	"/": typeof IndexLazyRoute
	"/$pageId": typeof PageIdRoute
	"/interactive-content-designer": typeof InteractiveContentDesignerRoute
	"/onboarding": typeof OnboardingLazyRoute
	"/preview": typeof PreviewLazyRoute
}

export interface FileRoutesById {
	__root__: typeof rootRoute
	"/": typeof IndexLazyRoute
	"/$pageId": typeof PageIdRoute
	"/interactive-content-designer": typeof InteractiveContentDesignerRoute
	"/onboarding": typeof OnboardingLazyRoute
	"/preview": typeof PreviewLazyRoute
}

export interface FileRouteTypes {
	fileRoutesByFullPath: FileRoutesByFullPath
	fullPaths: "/" | "/$pageId" | "/interactive-content-designer" | "/onboarding" | "/preview"
	fileRoutesByTo: FileRoutesByTo
	to: "/" | "/$pageId" | "/interactive-content-designer" | "/onboarding" | "/preview"
	id: "__root__" | "/" | "/$pageId" | "/interactive-content-designer" | "/onboarding" | "/preview"
	fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
	IndexLazyRoute: typeof IndexLazyRoute
	PageIdRoute: typeof PageIdRoute
	InteractiveContentDesignerRoute: typeof InteractiveContentDesignerRoute
	OnboardingLazyRoute: typeof OnboardingLazyRoute
	PreviewLazyRoute: typeof PreviewLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
	IndexLazyRoute: IndexLazyRoute,
	PageIdRoute: PageIdRoute,
	InteractiveContentDesignerRoute: InteractiveContentDesignerRoute,
	OnboardingLazyRoute: OnboardingLazyRoute,
	PreviewLazyRoute: PreviewLazyRoute,
}

export const routeTree = rootRoute._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$pageId",
        "/interactive-content-designer",
        "/onboarding",
        "/preview"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/$pageId": {
      "filePath": "$pageId.tsx"
    },
    "/interactive-content-designer": {
      "filePath": "interactive-content-designer.tsx"
    },
    "/onboarding": {
      "filePath": "onboarding.lazy.tsx"
    },
    "/preview": {
      "filePath": "preview.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
