AWSTemplateFormatVersion: 2010-09-09
Description: >-
  store-backend

Transform:
  - AWS::Serverless-2016-10-31

Globals:
  Api:
    Cors:
      AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
      AllowHeaders: "'content-type'"
      AllowOrigin: "'*'"

Resources:
  DefineAuthChallenge:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/auth/define-auth-challenge/define-auth-challenge.defineAuthChallengeHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
    Metadata: #Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - src/auth/define-auth-challenge/define-auth-challenge.ts

  UserPoolDefineAuthChallengeLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:invokeFunction
      Principal: cognito-idp.amazonaws.com
      FunctionName: !GetAtt DefineAuthChallenge.Arn
      SourceArn: !GetAtt JigJoyUserPool.Arn

  CreateAuthChallenge:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/auth/create-auth-challenge/create-auth-challenge.createAuthChallengeHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
    Metadata: #Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - src/auth/create-auth-challenge/create-auth-challenge.ts

  UserPoolCreateAuthChallengeLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:invokeFunction
      Principal: cognito-idp.amazonaws.com
      FunctionName: !GetAtt CreateAuthChallenge.Arn
      SourceArn: !GetAtt JigJoyUserPool.Arn

  VerifyAuthChallengeResponse:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/auth/verify-auth-challenge-response/verify-auth-challenge-response.verifyAuthChallengeResponseHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Environment:
        Variables:
          KMS_KEY_ID: !Ref EncryptionKey
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action: kms:Decrypt
              Resource: !GetAtt EncryptionKey.Arn
    Metadata: #Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - src/auth/verify-auth-challenge-response/verify-auth-challenge-response.ts

  UserPoolVerifyAuthChallengeResponseLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:invokeFunction
      Principal: cognito-idp.amazonaws.com
      FunctionName: !GetAtt VerifyAuthChallengeResponse.Arn
      SourceArn: !GetAtt JigJoyUserPool.Arn

  PreSignUp:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/auth/pre-sign-up/pre-sign-up.preSignUpHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
    Metadata: #Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - src/auth/pre-sign-up/pre-sign-up.ts

  UserPoolPreSignUpLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:invokeFunction
      Principal: cognito-idp.amazonaws.com
      FunctionName: !GetAtt PreSignUp.Arn
      SourceArn: !GetAtt JigJoyUserPool.Arn

  PostAuthentication:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/auth/post-authentication/post-authentication.postAuthenticationHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Policies:
      - Statement:
        - Sid: AttributesUpdate
          Effect: Allow
          Action:
          - cognito-idp:AdminUpdateUserAttributes
          Resource: '*'
    Metadata: #Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - src/auth/post-authentication/post-authentication.ts

  UserPoolPostAuthenticationLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:invokeFunction
      Principal: cognito-idp.amazonaws.com
      FunctionName: !GetAtt PostAuthentication.Arn
      SourceArn: !GetAtt JigJoyUserPool.Arn

  EncryptionKey:
    Type: AWS::KMS::Key
    Properties:
      Enabled: true
      EnableKeyRotation: true
      KeyPolicy:
        Version: "2012-10-17"
        Id: key-default-1
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action: kms:*
            Resource: "*"
      MultiRegion: false
      PendingWindowInDays: 7

  # User Pool
  JigJoyUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: userPool
      Policies:
        PasswordPolicy:
          MinimumLength: 8
      UsernameAttributes:
        - email
      Schema:
        - AttributeDataType: String
          Name: email
          Required: true
        - AttributeDataType: String
          Mutable: true
          Required: false
          Name: authChallenge
      LambdaConfig:
        CreateAuthChallenge: !GetAtt CreateAuthChallenge.Arn
        DefineAuthChallenge: !GetAtt DefineAuthChallenge.Arn
        PreSignUp: !GetAtt PreSignUp.Arn
        PostAuthentication: !GetAtt PostAuthentication.Arn
        VerifyAuthChallengeResponse: !GetAtt VerifyAuthChallengeResponse.Arn

  # Domain For Sending Confirmation Email
  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      UserPoolId: !Ref JigJoyUserPool
      Domain: "jigjoy-user-pool-domain"

  # Web Client
  WebClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref JigJoyUserPool
      ClientName: webClient
      ExplicitAuthFlows:
        - ALLOW_CUSTOM_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      PreventUserExistenceErrors: ENABLED

  sendMagicLinkFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/auth/send-magic-link/send-magic-link.sendMagicLinkHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Send magic link to user email
      Environment:
        Variables:
          KMS_KEY_ID: !Ref EncryptionKey
          USER_POOL_ID: !Ref JigJoyUserPool
          SES_FROM_ADDRESS: team@jigjoy.io
          BASE_URL: http://jigjoy-dev.s3-website-eu-west-1.amazonaws.com
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action: ses:SendEmail
              Resource: "*"
            - Effect: Allow
              Action: kms:Encrypt
              Resource: !GetAtt EncryptionKey.Arn
            - Effect: Allow
              Action:
                [
                  "cognito-idp:AdminUpdateUserAttributes",
                  "cognito-idp:AdminGetUser",
                  "cognito-idp:AdminCreateUser",
                ]
              Resource: !GetAtt JigJoyUserPool.Arn
      Events:
        Api:
          Type: Api
          Properties:
            Path: /send-magic-link/
            Method: POST
    Metadata: #Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - src/auth/send-magic-link/send-magic-link.ts

  createPageFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/adapters/primary/create-page/create-page-adapter.createPageHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Create a new page
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PageTable
      Environment:
        Variables:
          PAGE_TABLE: !Ref PageTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: POST
    Metadata: #Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - src/adapters/primary/create-page/create-page-adapter.ts

  migrationOldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/adapters/primary/migration/migration-support-changing-carousel-buttons.migrateNavigationButtonsHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Migrate pages
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PageTable
      Environment:
        Variables:
          PAGE_TABLE: !Ref PageTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /migrate
            Method: POST
    Metadata: #Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - src/adapters/primary/migration/migration-support-changing-carousel-buttons.ts

  retrievePageFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/adapters/primary/retrieve-page/retrieve-page-adapter.retrievePageHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Retrieve a page based on id and environement
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PageTable
      Environment:
        Variables:
          PAGE_TABLE: !Ref PageTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{id}
            Method: GET
    Metadata: #Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - src/adapters/primary/retrieve-page/retrieve-page-adapter.ts

  accessPageFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/adapters/primary/access-page/access-page-adapter.accessPageHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Access a production page for given development page
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PageTable
      Environment:
        Variables:
          PAGE_TABLE: !Ref PageTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /access/{id}
            Method: GET
    Metadata: #Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - src/adapters/primary/access-page/access-page-adapter.ts

  retrievePagesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/adapters/primary/retrieve-pages/retrieve-pages-adapter.retrievePagesHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Retrieve createor's pages
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PageTable
      Environment:
        Variables:
          PAGE_TABLE: !Ref PageTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /pages/{origin}
            Method: GET
    Metadata: #Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - src/adapters/primary/retrieve-pages/retrieve-pages-adapter.ts

  updatePageFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/adapters/primary/update-page/update-page-adapter.updatePageHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Update existing page
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PageTable
      Environment:
        Variables:
          PAGE_TABLE: !Ref PageTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: PUT
    Metadata: #Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - src/adapters/primary/update-page/update-page-adapter.ts

  removePageFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/adapters/primary/remove-page/remove-page-adapter.removePageHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Remove page
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PageTable
      Environment:
        Variables:
          PAGE_TABLE: !Ref PageTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{id}
            Method: DELETE
    Metadata: #Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - src/adapters/primary/remove-page/remove-page-adapter.ts

  publishPageFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/adapters/primary/publish-page/publish-page-adapter.publishPageHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Publish page
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PageTable
      Environment:
        Variables:
          PAGE_TABLE: !Ref PageTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /publish
            Method: PUT
    Metadata: #Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - src/adapters/primary/publish-page/publish-page-adapter.ts

  PageTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      TableName: Page
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: origin
          AttributeType: S
        - AttributeName: environment
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: pageGSI
          KeySchema:
            - AttributeName: origin
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: environmentGSI
          KeySchema:
            - AttributeName: environment
              KeyType: HASH
          Projection:
            ProjectionType: ALL

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
