
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  store-backend

Transform:
- AWS::Serverless-2016-10-31

Globals:
  Api:
    Cors:
      AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
      AllowHeaders: "'content-type'"
      AllowOrigin: "'*'"

Resources:

  createNewPageFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/adapters/primary/create-page/create-page-adapter.createPageHandler
      Runtime: nodejs20.x
      Architectures:
      - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Create a new page
      Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref PageTable
      Environment:
        Variables:
          PAGE_TABLE: !Ref PageTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /new/
            Method: POST
    Metadata: #Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - src/adapters/primary/create-page/create-page-adapter.ts

  retrievePageFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/adapters/primary/retrieve-page/retrieve-page-adapter.retrievePageHandler
      Runtime: nodejs20.x
      Architectures:
      - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Retrieve a page based on id and environement
      Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref PageTable
      Environment:
        Variables:
          PAGE_TABLE: !Ref PageTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /new/{id}
            Method: GET
    Metadata: #Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - src/adapters/primary/retrieve-page/retrieve-page-adapter.ts

  updateNewPageFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/adapters/primary/update-page/update-page-adapter.updatePageHandler
      Runtime: nodejs20.x
      Architectures:
      - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Update existing page
      Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref PageTable
      Environment:
        Variables:
          PAGE_TABLE: !Ref PageTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /new/
            Method: PUT
    Metadata: #Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - src/adapters/primary/update-page/update-page-adapter.ts

  getPagesByOriginHandler:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get-pages-by-origin.getPagesByOriginHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Get pages by origin
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PageTable
      Environment:
        Variables:
          PAGE_TABLE: !Ref PageTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /pages/{origin}
            Method: GET

  PageTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Page
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: origin
        AttributeType: S
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
      GlobalSecondaryIndexes:
      - IndexName: pageGSI
        KeySchema:
        - AttributeName: origin
          KeyType: HASH
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 2
          WriteCapacityUnits: 2

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
